spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/catherine
    username: catherine
    password: 13243142
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.goodsoft.catherinebe.entity
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
logging:
  level:
    org:
      springframework:
        security: TRACE
