ALTER TABLE bookings
    ADD COLUMN admin_id INTEGER NOT NULL DEFAULT 1;

ALTER TABLE bookings
    ALTER COLUMN admin_id DROP DEFAULT;

ALTER TABLE bookings
    ADD COLUMN room_id INTEGER;

ALTER TABLE bookings
    ADD COLUMN status_id INTEGER NOT NULL DEFAULT 1 REFERENCES statuses;
