DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles
(
    id   BIGSERIAL,
    name CHARACTER VARYING(25) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

INSERT INTO roles (name)
VALUES ('ADMIN'),
       ('USER');
