ALTER TABLE bookings
    ADD COLUMN admin_id BIGINT;

ALTER TABLE bookings
    ADD COLUMN room_id INTEGER;

ALTER TABLE bookings
    ADD COLUMN status_id INTEGER NOT NULL DEFAULT 1 REFERENCES statuses;
